[workspace]
members = ['soft_time_limit', 'voxel', 'main']

[profile.dev]
opt-level = 1

[patch.crates-io]
coreaudio-sys = { git = "https://github.com/RustAudio/coreaudio-sys.git", rev = "cf3a8321f461655a304ee8aa3139d5c5c88fd379" }